### PR TITLE
Content warning specification v00

### PR DESCRIPTION
**Pull request by cinnamon-bun**

### CODE REVIEW

**Comment by staltz** [comment]
In my opinion this proposal can progress to the next phase (whatever that is, is it merge?), as it's implemented in a few clients (Patchfox, Patchwork), and implementation for Manyverse is done too.

**Comment by cinnamon-bun** [comment]
I just learned that gatherings work differently - the original post is empty and all the content is piled on as subsequent messages?  The spec needs to be updated to reflect this.  I suppose the `contentWarning` belongs on the subsequent messages.

**Review by christianbundy — APPROVED** [review]
LGTM. I think this is good to merge as-is.

**Comment by christianbundy** [comment]
@tschudin Are drafts meant to be merged as soon as a PR is opened? I'm not familiar with the drafts review process for this repo.

**Pull request merged**
